apiVersion: 1

datasources:
  - name: IoT Postgres
    uid: iot-postgres
    type: postgres
    access: proxy
    url: postgres-db:5432
    database: iot_dashboard
    user: hive
    secureJsonData:
      password: hivepassword
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    isDefault: true
    editable: true
